version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: it_menu_db
    environment:
      POSTGRES_DB: ithub_menu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: it_menu_app
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ithub_menu
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_LIQUIBASE_ENABLED: true

volumes:
  postgres_data: