server.port=8082

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/ithub_menu
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog-master.yml

# Thymeleaf
spring.thymeleaf.cache=false